version: "3"
services:

  rabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"

  db:
    image: postgres:14-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${FLASK_POSTGRES_PASSWORD}
      POSTGRES_USER: ${FLASK_POSTGRES_USER}
      POSTGRES_DB: ${FLASK_POSTGRES_DB}


  mailer:
    build:
      context: mailer
    depends_on:
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_SERVER: ${MAIL_SERVER}

  tweetbot:
    build:
      context: tweetbot
    depends_on:
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
        TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
        TWITTER_API_KEY: ${TWITTER_API_KEY}
        TWITTER_API_SECRET_KEY: ${TWITTER_API_SECRET_KEY}

  sms:
    build:
      context: sms
    depends_on:
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
        TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
        TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}

  flask_blog:
    build:
      context: flask_blog
    depends_on:
      - rabbit
      - db
      - mailer
    ports:
      - "5000:5000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_TEST_DATABASE_URL: ${FLASK_TEST_DATABASE_URL}
      FLASK_DATABASE_URL: ${FLASK_DATABASE_URL}
      FLASK_TRACK_MODIFICATIONS: ${FLASK_TRACK_MODIFICATIONS}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_JWT_SECRET_KEY: ${FLASK_JWT_SECRET_KEY}    

  gateway:
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

volumes:
  postgres_data:
